package com.github.cage;

/**
 * Object generator.
 * 
 * @param <T>
 *            the type of objects generated by this class
 * 
 * @author akiraly
 */
public interface IGenerator<T> {
	/**
	 * Returns an object with type <code>T</code> on every call. The returned
	 * object does not have to be a new instance.
	 * 
	 * @return generated object
	 */
	T next();
}
